# -*- coding: utf-8 -*-
"""SMS_spam_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/cold-git/sms-spam-detection/blob/main/SMS_spam_detection.ipynb
"""

pip install pandas scikit-learn numpy

!wget https://raw.githubusercontent.com/justmarkham/pycon-2016-tutorial/master/data/sms.tsv

import pandas as pd

data = pd.read_csv("sms.tsv", sep="\t", names=["label","message"])

from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()

X = vectorizer.fit_transform(data['message'])
y = data['label']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2
)

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)
print(accuracy)

test_msg = ["Congratulations you won a free iPhone click here"]

msg_vector = vectorizer.transform(test_msg)

prediction = model.predict(msg_vector)

print(prediction)

test_msg = ["Hi, this is Abdulsamad, how is your internship going?"]

msg_vector = vectorizer.transform(test_msg)

prediction = model.predict(msg_vector)

print(prediction)